<include xmlns:xacro="http://www.ros.org/wiki/xacro">
<xacro:macro name="platform">
<xacro:include filename="$(env MODELS_DIR)/common/utils.xacro" />
<xacro:include filename="$(env MODELS_DIR)/common/consts.xacro" />

<link name="platform">
    <visual name="platform_visual">
        <origin  xyz="0 0 ${0.05 - base_height/2}"/>
        <geometry>
            <mesh
                scale="0.01 0.01 0.01"
                filename="file:///$(env MODELS_DIR)/objects/platform/platform.stl"
            />
        </geometry>
        <material name="red">
            <color rgba="0.7 0 0 1.0"/>
        </material>
    </visual>

    <collision name="platform_collision">
        <geometry>
            <cylinder length="${base_height}" radius="0.15" />
        </geometry>
    </collision>
</link>

<link name="platform_weight">
    <inertial>
        <mass value="3.3" />
        <inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.037"/>
    </inertial>
</link>

<joint name="platform_weight_joint" type="fixed">
    <parent link="platform"/>
    <child link="platform_weight"/>
</joint>

<gazebo>
    <plugin
        filename="gz-sim-odometry-publisher-system"
        name="gz::sim::systems::OdometryPublisher">
        <odom_frame>/platform/odom</odom_frame>
        <robot_base_frame>platform</robot_base_frame>
        <odom_publish_frequency>20</odom_publish_frequency>
        <odom_topic>/platform/odom</odom_topic>
        <tf_topic>tf</tf_topic>
  </plugin>
</gazebo>

</xacro:macro>
</include>
