<?xml version="1.0" ?>
<sdf xmlns:xacro="http://www.ros.org/wiki/xacro" version="1.10">
<world name="infinistand_world">

<xacro:include filename="$(env MODELS_DIR)/common/simple_light.xacro" />
<xacro:include filename="$(env MODELS_DIR)/common/plugins.xacro" />
<xacro:include filename="$(env MODELS_DIR)/common/consts.xacro" />

<gravity>0 0 0</gravity>

<model name='flyer'>
    <include>
            <uri>file:/$(env MODELS_DIR)/flyer/flyer.urdf</uri>
            <pose>0.0 0.0 ${robot_side_len/2} 0.0 0 0.0</pose>
    </include>
</model>

</world>
</sdf>
