<?xml version="1.0" ?>
<sdf xmlns:xacro="http://www.ros.org/wiki/xacro" version="1.10">
<world name="walls_world">

<xacro:include filename="$(env MODELS_DIR)/common/simple_light.xacro" />
<xacro:include filename="$(env MODELS_DIR)/common/plugins.xacro" />
<xacro:include filename="$(env MODELS_DIR)/common/consts.xacro" />

<gravity>0 0 0</gravity>

<model name='flyer'>
    <include>
            <uri>file:/$(env MODELS_DIR)/flyers/full/flyer.urdf</uri>
            <pose>0 0 ${robot_side_len_full/2} 0 0 0</pose>
    </include>
</model>

<model name='floor'>
    <pose>1 0 2 0 ${pi / 2} ${pi}</pose>
    <include>
        <uri>file:/$(env MODELS_DIR)/objects/wall/100-panels/105</uri>
        <pose>0 0 0 0 0 0</pose>
    </include>
    <include>
        <uri>file:/$(env MODELS_DIR)/objects/wall/100-panels/106</uri>
        <pose>0.503 0 0 0 0 0</pose>
    </include>
    <include>
        <uri>file:/$(env MODELS_DIR)/objects/wall/100-panels/107</uri>
        <pose>1.073 0 0 0 0 0</pose>
    </include>
    <include>
        <uri>file:/$(env MODELS_DIR)/objects/wall/100-panels/108</uri>
        <pose>1.723 0 0 0 0 0</pose>
    </include>
</model>

</world>
</sdf>
