<?xml version="1.0"?>
<robot name="airstand" xmlns:xacro="http://www.ros.org/wiki/xacro">

<xacro:include filename="$(env MODELS_DIR)/common/utils.xacro" />
<xacro:include filename="$(env MODELS_DIR)/platform/platform.xacro" />
<xacro:include filename="$(env MODELS_DIR)/flyer/flyer.xacro" />

<xacro:platform/>
<xacro:flyer/>

<joint name="platform_flyer_joint" type="fixed">
    <parent link="platform"/>
    <child link="base"/>
    <origin xyz="0 0 ${robot_side_len/2 + base_height/2}"/>
</joint>

</robot>
