<include xmlns:xacro="http://www.ros.org/wiki/xacro">
<xacro:macro name="platform">
<xacro:include filename="$(env MODELS_DIR)/common/utils.xacro" />

<link name="platform">
    <visual name="platform_visual">
        <origin  xyz="0 0 ${0.05 - base_height/2}"/>
        <geometry>
            <mesh
                scale="0.01 0.01 0.01"
                filename="file:///$(env MODELS_DIR)/platform/platform.stl"
            />
        </geometry>
        <material name="red">
            <color rgba="0.7 0 0 1.0"/>
        </material>
    </visual>

    <collision name="platform_collision">
        <geometry>
            <cylinder length="${base_height}" radius="${base_radius}" />
        </geometry>
    </collision>
</link>

<link name="platform_weight">
    <inertial>
        <mass value="3.3" />
        <inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.037"/>
    </inertial>
</link>

<joint name="platform_weight_joint" type="fixed">
    <parent link="platform"/>
    <child link="platform_weight"/>
</joint>

</xacro:macro>
</include>
