<include xmlns:xacro="http://www.ros.org/wiki/xacro">
<xacro:macro name="flyer">

<xacro:include filename="$(env MODELS_DIR)/common/utils.xacro" />
<xacro:include filename="$(env MODELS_DIR)/common/consts.xacro" />
<xacro:include filename="$(env MODELS_DIR)/flyers/propeller.xacro" />
<xacro:include filename="$(env MODELS_DIR)/flyers/sslidar.xacro" />

<xacro:property name="robot_side_len" value="${robot_side_len_full}" />
<xacro:property name="side_offset" value="0.07" />

<link name="base">
    <visual name="base_visual">
        <origin  xyz="0 ${robot_side_len/2 - 0.02} 0" rpy="0 0 ${pi / 2}"/>
        <geometry>
            <mesh filename="file:///$(env MODELS_DIR)/flyers/full/robot.stl" scale="0.001 0.001 0.001"/>
        </geometry>
        <material name="blue">
            <color rgba="0 0 0.7 1.0"/>
        </material>
    </visual>

    <collision name="base_collision">
        <origin  xyz="0 0 0"/>
        <geometry>
            <box size="${robot_side_len} ${robot_side_len} ${robot_side_len}" />
        </geometry>
    </collision>
</link>

<link name="base_weight">
    <xacro:cuboid_inertia weight="2" a="${robot_side_len}" b="${robot_side_len}" c="${robot_side_len}" />
    <visual name="base_visual">
        <geometry>
            <sphere radius="${robot_side_len/2 + 0.03}"/>
            <material name="red">
                <color rgba="1.0 0 0 1.0"/>
            </material>
        </geometry>
    </visual>
</link>

<joint name="base_weight_joint" type="fixed">
    <parent link="base"/>
    <child link="base_weight"/>
</joint>

<!-- IMU BLOCK-->
<link name="imu"></link>
<joint name="imu_joint" type="fixed">
    <parent link="base"/>
    <child link="imu"/>
</joint>
<gazebo reference="imu">
    <sensor name="imu" type="imu">
        <always_on>1</always_on>
        <update_rate>100</update_rate>
        <visualize>true</visualize>
        <topic>imu</topic>
        <enable_metrics>true</enable_metrics>
    </sensor>
</gazebo>
<!-- END IMU BLOCK-->

<!-- CAMERA BLOCK-->
<link name="camera"></link>
<joint name="camera_joint" type="fixed">
    <parent link="base"/>
    <child link="camera"/>
    <origin xyz="${robot_side_len/2 + 0.005} 0 ${side_offset}"/>
</joint>
<gazebo reference="camera">
    <sensor name="camera" type="camera">
        <camera>
            <horizontal_fov>1.047</horizontal_fov>
            <image>
                <width>320</width>
                <height>240</height>
            </image>
            <clip>
                <near>0.1</near>
                <far>100</far>
            </clip>
        </camera>
        <always_on>1</always_on>
        <update_rate>30</update_rate>
        <visualize>true</visualize>
        <topic>camera</topic>
    </sensor>
</gazebo>
<!-- END CAMERA BLOCK-->

<!-- LIDAR BLOCK-->
<xacro:sslidar name="fl" xyz="${robot_side_len/2} ${robot_side_len/2} 0" rpy="0 0 ${pi/4}"/>
<xacro:sslidar name="bl" xyz="${-robot_side_len/2} ${robot_side_len/2} 0" rpy="0 0 ${-pi/4 - pi}"/>
<xacro:sslidar name="fr" xyz="${robot_side_len/2} ${-robot_side_len/2} 0" rpy="0 0 ${-pi/4}"/>
<xacro:sslidar name="br" xyz="${-robot_side_len/2} ${-robot_side_len/2} 0" rpy="0 0 ${pi/4 + pi}"/>
<!-- END LIDAR BLOCK-->

<gazebo>
    <plugin
        filename="gz-sim-joint-state-publisher-system"
        name="gz::sim::systems::JointStatePublisher">
        <topic>joint_states</topic> <!--from <ros><remapping> -->
        <joint_name>prop_fl_joint</joint_name>
        <joint_name>prop_fr_joint</joint_name>
        <joint_name>prop_bl_joint</joint_name>
        <joint_name>prop_br_joint</joint_name>
        <joint_name>prop_rt_joint</joint_name>
        <joint_name>prop_rb_joint</joint_name>
        <joint_name>prop_lt_joint</joint_name>
        <joint_name>prop_lb_joint</joint_name>
        <joint_name>prop_ul_joint</joint_name>
        <joint_name>prop_ur_joint</joint_name>
        <joint_name>prop_dl_joint</joint_name>
        <joint_name>prop_dr_joint</joint_name>
  </plugin>
</gazebo>

<xacro:propeller name="prop_fl" xyz="${robot_side_len/2} ${side_offset} ${side_offset}" rpy="0 0 ${pi}"/>
<xacro:propeller name="prop_fr" xyz="${robot_side_len/2} ${-side_offset} ${-side_offset}" rpy="0 0 ${pi}"/>

<xacro:propeller name="prop_bl" xyz="${-robot_side_len/2} ${side_offset} ${-side_offset}" rpy="0 0 0"/>
<xacro:propeller name="prop_br" xyz="${-robot_side_len/2} ${-side_offset} ${side_offset}" rpy="0 0 0"/>

<xacro:propeller name="prop_rt" xyz="${side_offset} ${-robot_side_len/2} ${side_offset}" rpy="0 0 ${pi/2}"/>
<xacro:propeller name="prop_rb" xyz="${-side_offset} ${-robot_side_len/2} ${-side_offset}" rpy="0 0 ${pi/2}"/>

<xacro:propeller name="prop_lt" xyz="${-side_offset} ${robot_side_len/2} ${side_offset}" rpy="0 0 ${-pi/2}"/>
<xacro:propeller name="prop_lb" xyz="${side_offset} ${robot_side_len/2} ${-side_offset}" rpy="0 0 ${-pi/2}"/>

<xacro:propeller name="prop_ul" xyz="${-side_offset} ${side_offset} ${robot_side_len/2}" rpy="0 ${pi/2} 0"/>
<xacro:propeller name="prop_ur" xyz="${side_offset} ${-side_offset} ${robot_side_len/2}" rpy="0 ${pi/2} 0"/>

<xacro:propeller name="prop_dl" xyz="${side_offset} ${side_offset} ${-robot_side_len/2}" rpy="0 ${-pi/2} 0"/>
<xacro:propeller name="prop_dr" xyz="${-side_offset} ${-side_offset} ${-robot_side_len/2}" rpy="0 ${-pi/2} 0"/>

</xacro:macro>
</include>
