<?xml version="1.0" ?>
<sdf xmlns:xacro="http://www.ros.org/wiki/xacro" version="1.10">
<world name="infinistand_world">

<xacro:include filename="$(env MODELS_DIR)/common/simple_light.xacro" />
<xacro:include filename="$(env MODELS_DIR)/common/plugins.xacro" />
<xacro:include filename="$(env MODELS_DIR)/common/consts.xacro" />

<xacro:include filename="$(env MODELS_DIR)/objects/glass.xacro" />

<model name="Glass">
    <static>true</static>
    <xacro:glass_plate z="-0.01" w="100" l="100" thickness="0.02"/>
</model>

<model name='airstand'>
    <include>
        <uri>file:/$(env MODELS_DIR)/objects/platform/full_platform.urdf</uri>
        <pose>0.0 0.0 ${base_height/2 + 0.01} 0.0 0 0.0</pose>
    </include>
</model>

</world>
</sdf>
