<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="platform">

<xacro:include filename="$(env MODELS_DIR)/common/utils.xacro" />

<xacro:property name="base_height" value="0.07" />
<xacro:property name="base_radius" value="0.15" />
<xacro:property name="prof_height" value="0.4" />
<xacro:property name="prof_radius" value="0.03" />

<link name="base_link">
    <xacro:primitive name="base">
        <origin xyz="0 0 ${base_height / 2}" rpy="0 0 0" />
        <geometry><cylinder length="${base_height}" radius="${base_radius}"/></geometry>
    </xacro:primitive>

    <xacro:primitive name="prof">
        <origin xyz="0 0 ${base_height + prof_height / 2}" rpy="0 0 0" />
        <geometry><cylinder length="${prof_height}" radius="${prof_radius}"/></geometry>
    </xacro:primitive>

    <xacro:primitive name="plate">
        <origin xyz="0 0 ${base_height + prof_height}" rpy="0 0 0" />
        <geometry><box size="0.21 0.297 0.01"/></geometry>
    </xacro:primitive>

    <inertial>
        <origin rpy="0 0 0" xyz="0 0 1.0"/>
        <mass value="1"/>
        <inertia ixx="0.334" ixy="0.0" ixz="0.0" iyy="0.334" iyz="0.0" izz="0.0017"/>
    </inertial>
</link>

</robot>
