<?xml version="1.0"?>
<sdf xmlns:xacro="http://www.ros.org/wiki/xacro" version="1.10">
<model name="platform" canonical_link='base'>

<xacro:include filename="$(env MODELS_DIR)/common/utils.xacro" />
<xacro:include filename="propeller.xacro" />

<xacro:property name="base_height" value="0.59" />
<xacro:property name="base_radius" value="0.15" />

<link name="base">
    <visual name="base_visual">
        <pose>0 0 ${0.05 - base_height/2} 0 0 0</pose>
        <geometry>
            <mesh>
                <uri>file://$(env MODELS_DIR)/airstand/platform/platform.stl</uri>
                <scale>0.01 0.01 0.01</scale>
            </mesh>
        </geometry>
        <material>
            <diffuse>0 0 1</diffuse>
            <ambient>0 0 0.5</ambient>
            <specular>0 0 0.5</specular>
        </material>
    </visual>

    <collision name="base_collision">
        <geometry>
            <cylinder>
                <length>${base_height}</length>
                <radius>${base_radius}</radius>
            </cylinder>
        </geometry>
    </collision>

    <inertial>
        <mass>3.3</mass>
        <inertia>
            <ixx>0.334</ixx>
            <ixy>0</ixy>
            <ixz>0</ixz>
            <iyy>0.334</iyy>
            <iyz>0</iyz>
            <izz>0.0017</izz>
        </inertia>
    </inertial>
</link>

<xacro:propeller name="prop_left" side="1"/>
<xacro:propeller name="prop_right" side="-1"/>

</model>
</sdf>
