<?xml version="1.0"?>
<robot name="platform" xmlns:xacro="http://www.ros.org/wiki/xacro">

<xacro:include filename="$(env MODELS_DIR)/common/utils.xacro" />

<link name="base">
    <visual name="base_visual">
        <origin  xyz="0 0 ${0.05 - base_height/2}"/>
        <geometry>
            <mesh
                scale="0.01 0.01 0.01"
                filename="file:///$(env MODELS_DIR)/airstand/platform/platform.stl"
            />
        </geometry>
        <material name="blue">
            <color rgba="0 0 0.7 1.0"/>
        </material>
    </visual>

    <collision name="base_collision">
        <geometry>
            <cylinder length="${base_height}" radius="${base_radius}" />
        </geometry>
    </collision>
</link>

<link name="base_weight">
    <inertial>
        <mass value="3.3" />
        <inertia ixx="0.334" ixy="0" ixz="0" iyy="0.334" iyz="0" izz="0.0017"/>
    </inertial>
</link>

<joint name="base_weight_joint" type="fixed">
    <parent link="base"/>
    <child link="base_weight"/>
</joint>

<link name="imu"></link>
<joint name="imu_joint" type="fixed">
    <parent link="base"/>
    <child link="imu"/>
    <origin xyz="0 0 ${base_height/2}"/>
</joint>
<gazebo reference="imu">
    <sensor name="imu" type="imu">
        <always_on>1</always_on>
        <update_rate>100</update_rate>
        <visualize>true</visualize>
        <topic>platofrm/imu</topic>
        <enable_metrics>true</enable_metrics>
    </sensor>
</gazebo>

</robot>
