<include xmlns:xacro="http://www.ros.org/wiki/xacro">
<xacro:macro name="propeller" params="name side">
<xacro:if value="${side == 1}">
    <xacro:property name="motor_number" value="0" />
</xacro:if>
<xacro:if value="${side != 1}">
    <xacro:property name="motor_number" value="1" />
</xacro:if>

<link name="${name}">
    <inertial>
        <mass value="0.04" />
        <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.00007" iyz="0" izz="0.00006"/>
    </inertial>
    <visual name="prop_${name}_vis">
        <geometry>
            <box size="0.01 0.1 0.1"/>
        </geometry>
        <material name="red">
            <color rgba="1.0 0 0 1.0"/>
        </material>
    </visual>
</link>

<joint name="${name}_joint" type="revolute">
    <origin xyz="0 ${side * 0.17} ${-base_height/2 + 0.165}"/>
    <parent link="base"/>
    <child link="${name}"/>
    <axis xyz="1 0 0"/>
    <limit effort="100" velocity="100"/>
</joint>

<gazebo>
    <plugin
        filename="gz-sim-thruster-system"
        name="gz::sim::systems::Thruster">
        <joint_name>${name}_joint</joint_name>
        <use_angvel_cmd>true</use_angvel_cmd>
        <thrust_coefficient>0.001</thrust_coefficient>
        <fluid_density>1.225</fluid_density>
        <propeller_diameter>0.2</propeller_diameter>
        <velocity_control>false</velocity_control>
        <p_gain>0</p_gain>
        <d_gain>0</d_gain>
        <i_gain>0</i_gain>
    </plugin>
</gazebo>

</xacro:macro>
</include>
